[versions]
# libraries
annotations = "26.0.2"

# plugins
kotlin = "2.2.0"
changelog = "2.4.0"
intelliJPlatform = "2.10.4"
qodana = "2025.2.1"
kover = "0.9.3"
serialization = "1.9.0"
intellijPluginUploader = "1.3.5"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
intellijPluginUploader = { id = "dev.bmac.intellij.plugin-uploader", version.ref = "intellijPluginUploader" }
